### ISSUE TITLE
Discrete event simulation in Python

### ISSUE THREAD

**Issue by drvinceknight** [IanHawke/msc-or-python#4]
Perhaps you might be interested in adding http://ciw.readthedocs.io/ at some point?

This is a library developed by @geraintpalmer (student of mine). If it's of interest I'm sure he'd be happy to work on a PR.

**Comment by IanHawke** [comment]
It sounds good to me, but I'm working from a base of very little knowledge. I will ask @AEllina and the other OR people how useful this would be for the projects the students are running (maybe alongside the MC section?). Time constraints may make it a step too far.

**Comment by drvinceknight** [comment]
> I will ask @AEllina and the other OR people how useful this would be for the projects the students are running (maybe alongside the MC section?). Time constraints may make it a step too far.

I was thinking it could go somewhere in the MC section but yeah you're constrained for time. Let me know what @AEllina thinks. One option could be to add a (very) small paragraph with a very basic simulation of a queue and point at the documentation for further reading. :)

**Comment by AEllina** [comment]
Hi,

Due to limited time I went through just one of the examples that uses pulp
yesterday.

Today I used the Monte Carlo example with the bus route. I also showed them
the existing documentation on random sampling in python in case they need
to do random sampling from different distributions. The rest of today we
are going to focus more on pandas since most of the people asked us for
data handling examples.

Thanks,
Andria

**Comment by IanHawke** [comment]
Jörg says that discrete event simulation stuff would be a useful counterpoint to MC and that he knows that Geraint's doing really good stuff. So I'll add a link after we've done today, and then add a TODO in the final washup. Thanks!

**Comment by geraintpalmer** [comment]
Hi! happy to help on this where I can, let me know.

**Comment by IanHawke** [comment]
For now I've just added a comment at the start of the Monte Carlo methods (commit 0fbd702) which contrasts MC and DE methods, and a longer comment in the TODO (commit 77616d8f2f191a478a19d167a0090e459ab9f285) about how to balance this material next time. I may easily have committed crimes against accuracy in my descriptions of the methods here, so any input you can make on that would be great!

My feeling from the washup discussion (see commit 4b1241b) is that, within the 1 hour slot we allocated, either MC or DE would be really hard to get across well. Given the demand for data handling over simulation by the projects the students had, this wasn't well balanced. In future it would be far better if the `numpy` example or exercise could build straight into the MC/DE section, or it's just too much code for Python novices.
